// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIsjg6uVyH9Wv-jzwrQgDpEo5kiulugI',
    appId: '1:364626133532:web:78946b9f9e5586f4ed95d9',
    messagingSenderId: '364626133532',
    projectId: 'flutter-413a4',
    authDomain: 'flutter-413a4.firebaseapp.com',
    storageBucket: 'flutter-413a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfoDtYZGrGff3YpRBTMf-MAYBu8fp7jmg',
    appId: '1:364626133532:android:f243ae7bd0aa9678ed95d9',
    messagingSenderId: '364626133532',
    projectId: 'flutter-413a4',
    storageBucket: 'flutter-413a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ciB3irtVhKTlGLfFOM0CNzyTWGpLKHk',
    appId: '1:364626133532:ios:459d9859e30c61a1ed95d9',
    messagingSenderId: '364626133532',
    projectId: 'flutter-413a4',
    storageBucket: 'flutter-413a4.appspot.com',
    iosClientId: '364626133532-t6gdgk9ce6pu2l5cmqsc0jlbh2nvt9nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ciB3irtVhKTlGLfFOM0CNzyTWGpLKHk',
    appId: '1:364626133532:ios:459d9859e30c61a1ed95d9',
    messagingSenderId: '364626133532',
    projectId: 'flutter-413a4',
    storageBucket: 'flutter-413a4.appspot.com',
    iosClientId: '364626133532-t6gdgk9ce6pu2l5cmqsc0jlbh2nvt9nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
